### ISSUE TITLE
Dockerfile + docker-compose.yml

### ISSUE THREAD

**Issue by rodrigooler** [THAYLLER/apiRestNode#1]
Adicione os seguintes arquivos e configurações ao projeto.

- [x] Dockefile;
- [x] docker-compose.yml;

Exemplos

https://medium.com/statuscode/dockerising-a-node-js-and-mongodb-app-d22047e2806f
https://medium.com/@lameckanao/fazendo-um-crud-com-node-js-mongodb-e-docker-70ee6c8da8ca
https://hackernoon.com/build-a-crud-api-with-mongodb-express-and-docker-70510c6f706b
https://www.youtube.com/watch?v=AVNADGzXrrQ&t=913s

**Comment by THAYLLER** [comment]
para completar essa issue criei uma nova bransh
